"""Create assessments table

Revision ID: 2af0b30098bb
Revises: 88a8d1f3c2a3
Create Date: 2026-07-08 19:09:52.984013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2af0b30098bb'
down_revision: Union[str, Sequence[str], None] = '88a8d1f3c2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_parcels_gpin'), 'parcels', ['gpin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcels_gpin'), table_name='parcels')
    # ### end Alembic commands ###
