"""Add owner fields to parcels

Revision ID: 35aca5809938
Revises: de78e56270e3
Create Date: 2026-07-08 19:32:08.684481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35aca5809938'
down_revision: Union[str, Sequence[str], None] = 'de78e56270e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('owner_address', sa.String(length=255), nullable=True))
    op.add_column('parcels', sa.Column('owner_city_state', sa.String(length=255), nullable=True))
    op.add_column('parcels', sa.Column('owner_zip_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parcels', 'owner_zip_code')
    op.drop_column('parcels', 'owner_city_state')
    op.drop_column('parcels', 'owner_address')
    # ### end Alembic commands ###
