"""Add street_number street_name unit to parcels

Revision ID: 73e36a59ac3c
Revises: b5a50e6e2b6e
Create Date: 2026-07-08 17:35:08.517394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e36a59ac3c'
down_revision: Union[str, Sequence[str], None] = 'b5a50e6e2b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('street_number', sa.String(length=20), nullable=True))
    op.add_column('parcels', sa.Column('street_name', sa.String(length=255), nullable=True))
    op.add_column('parcels', sa.Column('unit', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_parcels_street_name'), 'parcels', ['street_name'], unique=False)
    op.create_index(op.f('ix_parcels_street_number'), 'parcels', ['street_number'], unique=False)
    op.create_index(op.f('ix_parcels_unit'), 'parcels', ['unit'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcels_unit'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_street_number'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_street_name'), table_name='parcels')
    op.drop_column('parcels', 'unit')
    op.drop_column('parcels', 'street_name')
    op.drop_column('parcels', 'street_number')
    # ### end Alembic commands ###
