"""Create parcels table

Revision ID: c0819cec8d89
Revises: 
Create Date: 2026-07-08 02:04:05.570921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0819cec8d89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_number', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('mailing_address', sa.String(length=255), nullable=True),
    sa.Column('zoning', sa.String(length=50), nullable=True),
    sa.Column('lot_size', sa.Float(), nullable=True),
    sa.Column('land_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('improvement_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_assessment', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcels_id'), 'parcels', ['id'], unique=False)
    op.create_index(op.f('ix_parcels_parcel_number'), 'parcels', ['parcel_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcels_parcel_number'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_id'), table_name='parcels')
    op.drop_table('parcels')
    # ### end Alembic commands ###
