"""Create assessments table

Revision ID: de78e56270e3
Revises: 2af0b30098bb
Create Date: 2026-07-08 19:14:07.925219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de78e56270e3'
down_revision: Union[str, Sequence[str], None] = '2af0b30098bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_number', sa.String(length=50), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('land_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('improvement_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['parcel_number'], ['parcels.parcel_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.create_index(op.f('ix_assessments_parcel_number'), 'assessments', ['parcel_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessments_parcel_number'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
